= CS3103_p2p

== Protocol Design (Without NAT, with central tracker)

=== Communication between tracker and p2p client

The centralised server (tracker) will be running on UDP Port 80.

It will contain a list, where each entry will be in the form _(filename, chunk_num, host)_. A host
that does not have a chunk, but participates in the torrent/swarm, will have their _chunk_num_ value be _NULL_.

Suppose Harry wants to download a file _test.txt_, he will send the server a request. The tracker will update
its list to include _(test.txt, NULL, Harry's IP)_, and respond to Harry a list of entries, where _filename_ is equal
to _test.txt_.

For every chunk Harry has successfully downloaded, he will inform the tracker and the tracker will
update its list to include _(test.txt, chunk_no, Harry's IP)_.

Suppose Harry wants to exit from the swarm, he will inform the tracker and the tracker will delete the entries corresponding
to Harry.

Suppose Harry wants to upload a *new* file, he will send the tracker the new file. The tracker will divide the file
into chunks of fixed size, say 2048 bytes, and update its list.

Every 15 seconds, each peer will ask the tracker for the updated list, so that each peer knows which peer has which chunk
and which peer has exited from the swarm.

Any peer can query the tracker a list of files available or to query for a specified file.

==== Tracker request format

----
Format: REQUEST <FIELD> [<FILENAME>] [<CHUNK NO>] [<IP ADDRESS>]
----

FIELD VALUES (values from 1 to 7)

. Download a file from the swarm. FILENAME and IP ADDRESS values must be filled.
. Ask the tracker for the updated list (every 15 seconds). FILENAME must be filled.
. Inform the tracker that a chunk has been successfully downloaded. FILENAME and CHUNK NO must be filled.
. Upload a new file. FILENAME and IP ADDRESS must be filled.
. Exit from swarm. IP ADDRESS must be filled.
. Query the tracker for a list of files available.
. Query for a specified file. FILENAME must be filled.

==== Tracker response format

----
Format: RESPONSE <LIST OF ENTRIES>
----

----
Format: RESPONSE <LIST OF FILES>
----

----
Format: RESPONSE <SPECIFIED FILE>
----

=== Communication between p2p client and p2p server

Each P2P server will be running on TCP Port 6881.

When Harry wants to download a file, he will obtain a list from tracker.

At the start, he will simply choose a random chunk from a random peer to download.

Next, he will choose which chunks he does not have yet and from these chunks, randomly download one from a random peer.

There is a possibility that the chunk download from a peer will fail (eg. when the other peer exits). In this case, Harry
will (a) ask the tracker for the new updated list and (b) randomly choose **another** peer to download the same chunk.